### ISSUE TITLE
use PHP 7.x

### ISSUE THREAD

**Issue by ximex** [BaileySN/Docker_Admidio#2]
Use PHP 7.1 or PHP 7.0 instead of PHP 5.x

**Comment by Brawn1** [comment]
I use Debian 8.x, so PHP 5.x is the default. 
Next time, i build a new Docker version with Alpine and PHP 7.x with Apache2 or Nginx.

**Comment by ximex** [comment]
Maybe use something of this:
https://hub.docker.com/_/php/
https://hub.docker.com/_/nginx/

**Comment by Brawn1** [comment]
now in branch debian_9.
